# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='descriptiopn',
            new_name='description',
        ),
    ]
